version: '3.1'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    command: "--innodb_use_native_aio=0"
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - "./data.d:/var/lib/mysql"

  webapp:
    image: se441/spring-petclinic:both
    ports: 
      - "8484:8080/tcp"
    depends_on:
      - mysql